### ISSUE TITLE
Add exclusive online comtent

### ISSUE THREAD

**Issue by LarryHI** [polypmer/DemocracyDroid#26] opened 2017-02-11 04:08 UTC
More and more frequently interviews are being continued on the web. DN does not include these in their RSS feed. It would be way cool if your app could include these somehow.

**Comment by polypmer** [comment] 2017-02-11 13:32
Hi @LarryHI ! About this, (you're not the first to ask) if you scroll down to the bottom of the broadcast feed, are those videos what you're looking for? I've told others to look there in the past, but I'm not sure if these are the exclusive online content y'all are interested in.

**Comment by LarryHI** [comment] 2017-02-11 18:52
Thanks for your reply!

Let's see... Friday 2/10 ended with this segment:

https://www.democracynow.org/2017/2/10/white_supremacists_li
nked_to_the_real

Scrolling to the end of it, Amy says that the conversation will 
continue on-line and gives this link:

https://www.democracynow.org/2017/2/10/see_the_signs_of_terr
or_journalists

I don't see that in the app.

Now, having said that, what I mean is that I can't just go 
somewhere to see Friday's on-line only content.  If I happen to 
remember which segment on which day it was, I can find it from 
the app. So for Friday, going to the story at the top of the app at 
the moment and scrolling all the way down, well almost all the 
way, there is a link, and that link opens in my browser.

Or, alternatively, if I am looking for the rest of an interview with 
someone I have to go to my desktop or phone browser to this 
page:

https://www.democracynow.org/categories/web_exclusive

There is no RSS feed for that page that I can find (there is one, 
but it is DN's main RSS feed in the footer). I have emailed them 
several times to see if they could just put an RSS feed on that 
page! No reply.

There are also web services that construct an RSS feed. Last time 
I tried them, they did not handle media. I asked one of the 
developers and was told that they might consider it in the future. I 
haven't checked back recently but can see why they might not 
want to do that.

I just fired off one more email to DN asking for an RSS feed to 
that page. If they should reply, I'll let you know, but I'm not 
holding my breath.

Thanks for creating such a useful app.

--Larry




On 11 Feb 2017 at 5:32, Fenimore - notifications@github.com 
wrote:

Hi @LarryHI ! About this, (you're not the first to ask) if you scroll down to the 
bottom of the broadcast feed, are those videos what you're looking for? I've told 
others to look there in the past, but I'm not sure if these are the exclusive 
online content y'all are interested in.
-

**Comment by polypmer** [comment] 2017-02-12 01:09
Hi! Thanks for all this info! Yes there used to be something like a democracy now blog RSS, with all sorts of goodies (in the play store screenshots actually), but they've since been removed. I'm rushing to put together an update soon with some other fixes, as I start work soon. So I'll keep an eye out for this, but I can't promise any clever fix anytime soon. 

But tomorrow I'll look into fixing that it opens in the browser, and in the RSS feed footer. 

For the future, in any case, I suspect a third tab/category might be in order. What do you think about that?maybe leaving it on the bottom suffices?

**Comment by LarryHI** [comment] 2017-02-12 03:47
I have only limited experience with your app, but I'm thinking that 
it would be good to have a tab on top, and probably easier to write 
the code for that as well.  Essentially you'd be reading that web 
page, the one with the on-line content.

If someone is reading a transcript they can just click the link, but 
if they are listening to the audio or watching the video, all they 
have is Amy saying that they'll continue the interview and look for 
it on the website.

In that case, a user would click on your top tab and be taken to 
the on-line content page where, if they had already posted it, the 
continuation would appear.

It's too bad they don't provide an RSS feed, because one day they 
will change their web page and your app will be broken. An RSS 
feed would be continuous across web page changes.  I did email 
one last time, and if I get a positive reply on it, I'll let you know.

Anyway, that's my thinking.

--Larry



On 11 Feb 2017 at 17:09, Fenimore - notifications@github.com 
wrote:

Hi! Thanks for all this info! Yes there used to be something like a democracy 
now blog RSS, with all sorts of goodies (in the play store screenshots actually), 
but they've since been removed. I'm rushing to put together an update soon 
with some other fixes, as I start work soon. So I'll keep an eye out for this, but 
I can't promise any clever fix anytime soon.
But tomorrow I'll look into fixing that it opens in the browser, and in the RSS 
feed footer.
For the future, in any case, I suspect a third tab/category might be in order. 
What do you think about that?maybe leaving it on the bottom suffices?
-

**Comment by polypmer** [comment] 2017-02-12 14:09
Okie dokie, what about making the top button, the globe, link to the web exclusive content page? So that way you have a shortcut there. 

Also, you mentioned 
> almost all the way, there is a link, and that link opens in my browser

I can't reproduce this, for me the link opens in the video player

**Comment by LarryHI** [comment] 2017-02-13 18:27
On what app the link opens, it might depend on the default app 
settings and what version of Android it is.

Since the link is to a video file, opening in the video player is 
probably even better than opening in a browser. 

I don't remember if I clicked on the link in your app or from their 
web page in a browser. Doesn't matter, going to the video player 
sounds good to me.

On whether globe or tab, I defer to your better judgment. My 
feeling is that if Broadcast is a tab, then on-line content is in 
counterpoint to that, so should logically be a navigation tab. 
Maybe right next to the Broadcast tab, but that's not important. I 
guess this would make your tabs scroll left/right since they won't 
all fit on the screen (at least, on my screen).

--Larry



On 12 Feb 2017 at 6:09, Fenimore - notifications@github.com 
wrote:

Okie dokie, what about making the top button, the globe, link to the web 
exclusive content page? So that way you have a shortcut there.
Also, you mentioned
almost all the way, there is a link, and that link opens in my 
browser
I can't reproduce this, for me the link opens in the video player
-

**Comment by LarryHI** [comment] 2017-03-08 23:51
I forgot to email that I've been using DemocracyDroid with the 
web exclusive articles. It works fine!

I have to use it more, but I really like your app.

Perhaps it will end up one day in the App Store for users who don't 
use F-Droid?

Thanks
--Larry



On 12 Feb 2017 at 6:09, Fenimore - notifications@gith wrote:

Okie dokie, what about making the top button, the globe, link to the web 
exclusive content page? So that way you have a shortcut there.
Also, you mentioned
almost all the way, there is a link, and that link opens in my 
browser
I can't reproduce this, for me the link opens in the video player
-

**Comment by polypmer** [comment] 2017-03-09 01:32
Great! I'm glad it's working OK! And actually the app is already on the Play Store :)

So if this solution (putting web exclusives in the options menu) works, I'll close the issue. Thanks for your feedback!

**Closed by polypmer** 2017-03-09 01:32 UTC
Labels: enhancement
